language: node_js
node_js:
  - 10
services:
  - postgresql
cache:
  directories:
    - node_modules
script:
  - npm run test:travis --prefix server
before_install:
  - psql -c 'create database test;' -U postgres
  - npm install --prefix server
  - npm run test:migrate --prefix server
env:
  global:
    - POSTGRES_PORT="5432"
    - POSTGRES_PASSWORD=""
