version: "3"
services:
  postgres:
    image: postgres:10.3
    restart: always
    ports:
      - "3332:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ./docker-config/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
